Repository compserv/hknweb, pull requests merged in 2021-04, with the labels that each got.

#308 Bug Fix where Officer Hangout not tallying
  hknweb/candidate/utils.py
  hknweb/candidate/views.py
Labels: bug, frontend, high_priority

#301 Shortlinks Admin + On/Off Switch
  hknweb/shortlinks/admin.py
  hknweb/shortlinks/migrations/0003_auto_20210407_1409.py
  hknweb/shortlinks/models.py
  hknweb/shortlinks/urls.py
  hknweb/shortlinks/views.py
  hknweb/urls.py
Labels: feature

#307 Profile Settings Different Save Btn for Password and Edit Profile
  hknweb/templates/account/settings.html
  hknweb/views/users.py
Labels: bug, feature, frontend

#302 Add CSV mass requirement checkoffs + exec group role
  hknweb/admin.py
  hknweb/candidate/constants.py
  hknweb/candidate/templates/candidate/checkoffs.html
  hknweb/candidate/urls.py
  hknweb/candidate/views.py
  hknweb/init_permissions.py
  hknweb/settings/common.py
  hknweb/templates/base.html
  hknweb/views/users.py
Labels: feature

#309 Html submit duplicate submission + "Search" label to Alumni Search Button
  hknweb/alumni/templates/alumni/form.html
  hknweb/alumni/templates/alumni/search.html
  hknweb/candidate/templates/candidate/bitbyte.html
  hknweb/candidate/templates/candidate/candreq.html
  hknweb/candidate/templates/candidate/challenge_confirm.html
  hknweb/candidate/templates/candidate/officer_portal.html
  hknweb/elections/templates/elections/index.html
  hknweb/events/templates/events/all_rsvps.html
  hknweb/events/templates/events/event_form_base.html
  hknweb/events/templates/events/index.html
  hknweb/events/templates/events/show_details.html
  hknweb/exams/templates/exams/exams_add.html
  hknweb/exams/templates/exams/index.html
  hknweb/markdown_pages/templates/markdown_pages/editor.html
  hknweb/reviewsessions/templates/reviewsessions/index.html
  hknweb/reviewsessions/templates/reviewsessions/reviewsession_add.html
  hknweb/reviewsessions/templates/reviewsessions/reviewsession_edit.html
  hknweb/templates/account/signup.html
  hknweb/templates/registration/login.html
  hknweb/tutoring/templates/tutoring/coursepref.html
  hknweb/tutoring/templates/tutoring/index.html
  hknweb/tutoring/templates/tutoring/slotpref.html
Labels: bug, frontend
